In this Jupyter notebook we will focus on RANDOM USER and FRUTYVICE API Examples

### The RandomUser API  
Below are the get method parameters that we can generate  
- get_cell()
- get_city()
- get_dob()
- get_email()
- get_first_name()
- get_full_name()
- get_gender()
- get_id()
- get_id_number()
- get_id_type()
- get_info()
- get_last_name()
- get_login_md5()
- get_login_salt()
- get_login_sha1()
- get_login_sha256()
- get_nat()
- get_password()
- get_phone()
- get_picture()
- get_postcode()
- get_registered()
- get_state()
- get_street()
- get_username()
- get_zipcode()

In [5]:
# To start using the API install randomuser library
! pip install randomuser

Requirement already satisfied: randomuser in c:\users\16474\appdata\local\programs\python\python311\lib\site-packages (1.6)

[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
# loading the necessary libraries
import pandas as pd
from randomuser import RandomUser

In [7]:
# creating RandomUser object
r = RandomUser()

In [17]:
# using this function we get a list of 10 random users
some_list = r.generate_users(10)
some_list

[<randomuser.RandomUser at 0x1fd10012710>,
 <randomuser.RandomUser at 0x1fd10013510>,
 <randomuser.RandomUser at 0x1fd10012e10>,
 <randomuser.RandomUser at 0x1fd10012ad0>,
 <randomuser.RandomUser at 0x1fd10012c90>,
 <randomuser.RandomUser at 0x1fd10012b90>,
 <randomuser.RandomUser at 0x1fd10012d90>,
 <randomuser.RandomUser at 0x1fd10012bd0>,
 <randomuser.RandomUser at 0x1fd10012d10>,
 <randomuser.RandomUser at 0x1fd10012cd0>]

In [21]:
# Using get method parametes
name = r.get_full_name()
name

'Nicoline Nielsen'

In [23]:
# lets say we need 10 users with full name and email address, we can use for loop for the same
for user in some_list:
    print(user.get_full_name(), user.get_email())

Raul Schmitt raul.schmitt@example.com
Jim Rivera jim.rivera@example.com
Florian Vollmer florian.vollmer@example.com
Konrad Henrichs konrad.henrichs@example.com
Camille Roy camille.roy@example.com
Ava Taylor ava.taylor@example.com
Zachary Harcourt zachary.harcourt@example.com
Karl Woods karl.woods@example.com
Elliot Newman elliot.newman@example.com
ایلیا سهيلي راد yly.shylyrd@example.com

In [24]:
# generate photos of 10 random users

for user in some_list:
    print(user.get_picture())

https://randomuser.me/api/portraits/men/89.jpg
https://randomuser.me/api/portraits/men/96.jpg
https://randomuser.me/api/portraits/men/78.jpg
https://randomuser.me/api/portraits/men/32.jpg
https://randomuser.me/api/portraits/women/11.jpg
https://randomuser.me/api/portraits/women/36.jpg
https://randomuser.me/api/portraits/men/43.jpg
https://randomuser.me/api/portraits/men/9.jpg
https://randomuser.me/api/portraits/men/74.jpg
https://randomuser.me/api/portraits/men/88.jpg

In [27]:
# To generate a table with information about users, we can write a function containing all desirable parameters.
# The parameters will depend upon tests to be performed
# Then we call the get methods
# then return the pandas dataframe with users

def get_users():
    users = []
    for user in RandomUser.generate_users(10):
        users.append({"Name":user.get_full_name(),"Gender":user.get_gender(),"City":user.get_city(),"State":user.get_state(),"Email":user.get_email(), "DOB":user.get_dob(),"Picture":user.get_picture()})
    return pd.DataFrame(users)

In [28]:
get_users()

,Name,Gender,City,State,Email,DOB,Picture
0,Ronja Lampi,female,Utajärvi,Lapland,ronja.lampi@example.com,1993-07-30T11:47:31.824Z,https://randomuser.me/api/portraits/women/21.jpg
1,پارمیس احمدی,female,سنندج,کرمان,prmys.hmdy@example.com,1968-10-18T10:05:17.174Z,https://randomuser.me/api/portraits/women/26.jpg
2,Olive Zhang,female,Hastings,West Coast,olive.zhang@example.com,1996-01-24T23:52:21.603Z,https://randomuser.me/api/portraits/women/69.jpg
3,Luis Osullivan,male,Portarlington,Cork City,luis.osullivan@example.com,1973-08-25T00:50:58.751Z,https://randomuser.me/api/portraits/men/60.jpg
4,Sherilyn Van Lammeren,female,Maasdriel,Zeeland,sherilyn.vanlammeren@example.com,1977-07-16T21:32:46.995Z,https://randomuser.me/api/portraits/women/82.jpg
5,Oliver Puro,male,Karstula,Tavastia Proper,oliver.puro@example.com,1984-06-18T05:09:46.194Z,https://randomuser.me/api/portraits/men/85.jpg
6,Heinz-Otto Sahin,male,Helmbrechts,Bayern,heinz-otto.sahin@example.com,1979-04-01T00:57:45.832Z,https://randomuser.me/api/portraits/men/77.jpg
7,Yvonne Wells,female,Albany,New South Wales,yvonne.wells@example.com,1961-03-08T08:35:25.743Z,https://randomuser.me/api/portraits/women/9.jpg
8,پارسا کوتی,male,بندرعباس,گلستان,prs.khwty@example.com,1965-09-19T20:59:14.375Z,https://randomuser.me/api/portraits/men/33.jpg
9,Alyssa Robertson,female,Townsville,Queensland,alyssa.robertson@example.com,1994-04-22T01:35:35.265Z,https://randomuser.me/api/portraits/women/70.jpg

In [33]:
df1 = pd.DataFrame(get_users())  
df1.head()
# Hence now we have a pandas dataframe that can be used for testing purposes

,Name,Gender,City,State,Email,DOB,Picture
0,Jayden Harris,male,Palmerston North,Marlborough,jayden.harris@example.com,1990-07-03T06:24:10.855Z,https://randomuser.me/api/portraits/men/80.jpg
1,Victoria Nielsen,female,København Ø,Syddanmark,victoria.nielsen@example.com,1965-08-28T06:21:23.694Z,https://randomuser.me/api/portraits/women/78.jpg
2,Gustavo Lorenzo,male,Alcalá de Henares,Asturias,gustavo.lorenzo@example.com,1997-10-29T22:30:57.015Z,https://randomuser.me/api/portraits/men/95.jpg
3,Eemeli Remes,male,Kuhmoinen,Northern Ostrobothnia,eemeli.remes@example.com,1982-12-10T01:35:59.893Z,https://randomuser.me/api/portraits/men/46.jpg
4,Kent Fields,male,Chester,Strathclyde,kent.fields@example.com,1967-10-26T00:59:08.511Z,https://randomuser.me/api/portraits/men/82.jpg

### FRUTYVICE API

Another common way to use API is through requests library.

In [35]:
import requests
import json

In [36]:
# Obtaining the Frutyvice API data
data = requests.get("https://fruityvice.com/api/fruit/all")

In [38]:
# Retrieving the results
results = json.loads(data.text)
results

[{'name': 'Persimmon',
  'id': 52,
  'family': 'Ebenaceae',
  'order': 'Rosales',
  'genus': 'Diospyros',
  'nutritions': {'calories': 81,
   'fat': 0.0,
   'sugar': 18.0,
   'carbohydrates': 18.0,
   'protein': 0.0}},
 {'name': 'Strawberry',
  'id': 3,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Fragaria',
  'nutritions': {'calories': 29,
   'fat': 0.4,
   'sugar': 5.4,
   'carbohydrates': 5.5,
   'protein': 0.8}},
 {'name': 'Banana',
  'id': 1,
  'family': 'Musaceae',
  'order': 'Zingiberales',
  'genus': 'Musa',
  'nutritions': {'calories': 96,
   'fat': 0.2,
   'sugar': 17.2,
   'carbohydrates': 22.0,
   'protein': 1.0}},
 {'name': 'Tomato',
  'id': 5,
  'family': 'Solanaceae',
  'order': 'Solanales',
  'genus': 'Solanum',
  'nutritions': {'calories': 74,
   'fat': 0.2,
   'sugar': 2.6,
   'carbohydrates': 3.9,
   'protein': 0.9}},
 {'name': 'Pear',
  'id': 4,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Pyrus',
  'nutritions': {'calories': 57,
   'fat': 0.1,
   'sugar': 10.0,
   'carbohydrates': 15.0,
   'protein': 0.4}},
 {'name': 'Durian',
  'id': 60,
  'family': 'Malvaceae',
  'order': 'Malvales',
  'genus': 'Durio',
  'nutritions': {'calories': 147,
   'fat': 5.3,
   'sugar': 6.75,
   'carbohydrates': 27.1,
   'protein': 1.5}},
 {'name': 'Blackberry',
  'id': 64,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Rubus',
  'nutritions': {'calories': 40,
   'fat': 0.4,
   'sugar': 4.5,
   'carbohydrates': 9.0,
   'protein': 1.3}},
 {'name': 'Lingonberry',
  'id': 65,
  'family': 'Ericaceae',
  'order': 'Ericales',
  'genus': 'Vaccinium',
  'nutritions': {'calories': 50,
   'fat': 0.34,
   'sugar': 5.74,
   'carbohydrates': 11.3,
   'protein': 0.75}},
 {'name': 'Kiwi',
  'id': 66,
  'family': 'Actinidiaceae',
  'order': 'Struthioniformes',
  'genus': 'Apteryx',
  'nutritions': {'calories': 61,
   'fat': 0.5,
   'sugar': 9.0,
   'carbohydrates': 15.0,
   'protein': 1.1}},
 {'name': 'Lychee',
  'id': 67,
  'family': 'Sapindaceae',
  'order': 'Sapindales',
  'genus': 'Litchi',
  'nutritions': {'calories': 66,
   'fat': 0.44,
   'sugar': 15.0,
   'carbohydrates': 17.0,
   'protein': 0.8}},
 {'name': 'Pineapple',
  'id': 10,
  'family': 'Bromeliaceae',
  'order': 'Poales',
  'genus': 'Ananas',
  'nutritions': {'calories': 50,
   'fat': 0.12,
   'sugar': 9.85,
   'carbohydrates': 13.12,
   'protein': 0.54}},
 {'name': 'Fig',
  'id': 68,
  'family': 'Moraceae',
  'order': 'Rosales',
  'genus': 'Ficus',
  'nutritions': {'calories': 74,
   'fat': 0.3,
   'sugar': 16.0,
   'carbohydrates': 19.0,
   'protein': 0.8}},
 {'name': 'Gooseberry',
  'id': 69,
  'family': 'Grossulariaceae',
  'order': 'Saxifragales',
  'genus': 'Ribes',
  'nutritions': {'calories': 44,
   'fat': 0.6,
   'sugar': 0.0,
   'carbohydrates': 10.0,
   'protein': 0.9}},
 {'name': 'Passionfruit',
  'id': 70,
  'family': 'Passifloraceae',
  'order': 'Malpighiales',
  'genus': 'Passiflora',
  'nutritions': {'calories': 97,
   'fat': 0.7,
   'sugar': 11.2,
   'carbohydrates': 22.4,
   'protein': 2.2}},
 {'name': 'Plum',
  'id': 71,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Prunus',
  'nutritions': {'calories': 46,
   'fat': 0.28,
   'sugar': 9.92,
   'carbohydrates': 11.4,
   'protein': 0.7}},
 {'name': 'Orange',
  'id': 2,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 43,
   'fat': 0.2,
   'sugar': 8.2,
   'carbohydrates': 8.3,
   'protein': 1.0}},
 {'name': 'GreenApple',
  'id': 72,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Malus',
  'nutritions': {'calories': 21,
   'fat': 0.1,
   'sugar': 6.4,
   'carbohydrates': 3.1,
   'protein': 0.4}},
 {'name': 'Raspberry',
  'id': 23,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Rubus',
  'nutritions': {'calories': 53,
   'fat': 0.7,
   'sugar': 4.4,
   'carbohydrates': 12.0,
   'protein': 1.2}},
 {'name': 'Watermelon',
  'id': 25,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitales',
  'genus': 'Citrullus',
  'nutritions': {'calories': 30,
   'fat': 0.2,
   'sugar': 6.0,
   'carbohydrates': 8.0,
   'protein': 0.6}},
 {'name': 'Lemon',
  'id': 26,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 29,
   'fat': 0.3,
   'sugar': 2.5,
   'carbohydrates': 9.0,
   'protein': 1.1}},
 {'name': 'Mango',
  'id': 27,
  'family': 'Anacardiaceae',
  'order': 'Sapindales',
  'genus': 'Mangifera',
  'nutritions': {'calories': 60,
   'fat': 0.38,
   'sugar': 13.7,
   'carbohydrates': 15.0,
   'protein': 0.82}},
 {'name': 'Blueberry',
  'id': 33,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Fragaria',
  'nutritions': {'calories': 29,
   'fat': 0.4,
   'sugar': 5.4,
   'carbohydrates': 5.5,
   'protein': 0.0}},
 {'name': 'Apple',
  'id': 6,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Malus',
  'nutritions': {'calories': 52,
   'fat': 0.4,
   'sugar': 10.3,
   'carbohydrates': 11.4,
   'protein': 0.3}},
 {'name': 'Guava',
  'id': 37,
  'family': 'Myrtaceae',
  'order': 'Myrtales',
  'genus': 'Psidium',
  'nutritions': {'calories': 68,
   'fat': 1.0,
   'sugar': 9.0,
   'carbohydrates': 14.0,
   'protein': 2.6}},
 {'name': 'Apricot',
  'id': 35,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Prunus',
  'nutritions': {'calories': 15,
   'fat': 0.1,
   'sugar': 3.2,
   'carbohydrates': 3.9,
   'protein': 0.5}},
 {'name': 'Papaya',
  'id': 42,
  'family': 'Caricaceae',
  'order': 'Caricacea',
  'genus': 'Carica',
  'nutritions': {'calories': 43,
   'fat': 0.4,
   'sugar': 1.0,
   'carbohydrates': 11.0,
   'protein': 0.0}},
 {'name': 'Melon',
  'id': 41,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitaceae',
  'genus': 'Cucumis',
  'nutritions': {'calories': 34,
   'fat': 0.0,
   'sugar': 8.0,
   'carbohydrates': 8.0,
   'protein': 0.0}},
 {'name': 'Tangerine',
  'id': 77,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 45,
   'fat': 0.4,
   'sugar': 9.1,
   'carbohydrates': 8.3,
   'protein': 0.0}},
 {'name': 'Pitahaya',
  'id': 78,
  'family': 'Cactaceae',
  'order': 'Caryophyllales',
  'genus': 'Cactaceae',
  'nutritions': {'calories': 36,
   'fat': 0.4,
   'sugar': 3.0,
   'carbohydrates': 7.0,
   'protein': 1.0}},
 {'name': 'Lime',
  'id': 44,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 25,
   'fat': 0.1,
   'sugar': 1.7,
   'carbohydrates': 8.4,
   'protein': 0.3}},
 {'name': 'Pomegranate',
  'id': 79,
  'family': 'Lythraceae',
  'order': 'Myrtales',
  'genus': 'Punica',
  'nutritions': {'calories': 83,
   'fat': 1.2,
   'sugar': 13.7,
   'carbohydrates': 18.7,
   'protein': 1.7}},
 {'name': 'Dragonfruit',
  'id': 80,
  'family': 'Cactaceae',
  'order': 'Caryophyllales',
  'genus': 'Selenicereus',
  'nutritions': {'calories': 60,
   'fat': 1.5,
   'sugar': 8.0,
   'carbohydrates': 9.0,
   'protein': 9.0}},
 {'name': 'Grape',
  'id': 81,
  'family': 'Vitaceae',
  'order': 'Vitales',
  'genus': 'Vitis',
  'nutritions': {'calories': 69,
   'fat': 0.16,
   'sugar': 16.0,
   'carbohydrates': 18.1,
   'protein': 0.72}},
 {'name': 'Morus',
  'id': 82,
  'family': 'Moraceae',
  'order': 'Rosales',
  'genus': 'Morus',
  'nutritions': {'calories': 43,
   'fat': 0.39,
   'sugar': 8.1,
   'carbohydrates': 9.8,
   'protein': 1.44}},
 {'name': 'Feijoa',
  'id': 76,
  'family': 'Myrtaceae',
  'order': 'Myrtoideae',
  'genus': 'Sellowiana',
  'nutritions': {'calories': 44,
   'fat': 0.4,
   'sugar': 3.0,
   'carbohydrates': 8.0,
   'protein': 0.6}},
 {'name': 'Avocado',
  'id': 84,
  'family': 'Lauraceae',
  'order': 'Laurales',
  'genus': 'Persea',
  'nutritions': {'calories': 160,
   'fat': 14.66,
   'sugar': 0.66,
   'carbohydrates': 8.53,
   'protein': 2.0}},
 {'name': 'Kiwifruit',
  'id': 85,
  'family': 'Actinidiaceae',
  'order': 'Ericales',
  'genus': 'Actinidia',
  'nutritions': {'calories': 61,
   'fat': 0.5,
   'sugar': 8.9,
   'carbohydrates': 14.6,
   'protein': 1.14}},
 {'name': 'Cranberry',
  'id': 87,
  'family': 'Ericaceae',
  'order': 'Ericales',
  'genus': 'Vaccinium',
  'nutritions': {'calories': 46,
   'fat': 0.1,
   'sugar': 4.0,
   'carbohydrates': 12.2,
   'protein': 0.4}},
 {'name': 'Cherry',
  'id': 9,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Prunus',
  'nutritions': {'calories': 50,
   'fat': 0.3,
   'sugar': 8.0,
   'carbohydrates': 12.0,
   'protein': 1.0}},
 {'name': 'Peach',
  'id': 86,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Prunus',
  'nutritions': {'calories': 39,
   'fat': 0.25,
   'sugar': 8.4,
   'carbohydrates': 9.5,
   'protein': 0.9}},
 {'name': 'Jackfruit',
  'id': 94,
  'family': 'Moraceae',
  'order': 'Rosales',
  'genus': 'Artocarpus',
  'nutritions': {'calories': 95,
   'fat': 0.0,
   'sugar': 19.1,
   'carbohydrates': 23.2,
   'protein': 1.72}},
 {'name': 'Horned Melon',
  'id': 95,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitales',
  'genus': 'Cucumis',
  'nutritions': {'calories': 44,
   'fat': 1.26,
   'sugar': 0.5,
   'carbohydrates': 7.56,
   'protein': 1.78}},
 {'name': 'Hazelnut',
  'id': 96,
  'family': 'Betulaceae',
  'order': 'Fagales',
  'genus': 'Corylus',
  'nutritions': {'calories': 628,
   'fat': 61.0,
   'sugar': 4.3,
   'carbohydrates': 17.0,
   'protein': 15.0}},
 {'name': 'Pomelo',
  'id': 98,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 37,
   'fat': 0.0,
   'sugar': 8.5,
   'carbohydrates': 9.67,
   'protein': 0.82}},
 {'name': 'Mangosteen',
  'id': 99,
  'family': 'Clusiaceae',
  'order': 'Malpighiales',
  'genus': 'Garcinia',
  'nutritions': {'calories': 73,
   'fat': 0.58,
   'sugar': 16.11,
   'carbohydrates': 17.91,
   'protein': 0.41}}]

In [40]:
# Converting into a pandas dataframe
pd.DataFrame(results)
# Right now the data is in Nested JSON format. Look at the column Nutritions containing multiple sub columns, the data here needs to be flattened or normalize

,name,id,family,order,genus,nutritions
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,"{'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'c..."
1,Strawberry,3,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
2,Banana,1,Musaceae,Zingiberales,Musa,"{'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'c..."
3,Tomato,5,Solanaceae,Solanales,Solanum,"{'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'ca..."
4,Pear,4,Rosaceae,Rosales,Pyrus,"{'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'c..."
5,Durian,60,Malvaceae,Malvales,Durio,"{'calories': 147, 'fat': 5.3, 'sugar': 6.75, '..."
6,Blackberry,64,Rosaceae,Rosales,Rubus,"{'calories': 40, 'fat': 0.4, 'sugar': 4.5, 'ca..."
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,"{'calories': 50, 'fat': 0.34, 'sugar': 5.74, '..."
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,"{'calories': 61, 'fat': 0.5, 'sugar': 9.0, 'ca..."
9,Lychee,67,Sapindaceae,Sapindales,Litchi,"{'calories': 66, 'fat': 0.44, 'sugar': 15.0, '..."
10,Pineapple,10,Bromeliaceae,Poales,Ananas,"{'calories': 50, 'fat': 0.12, 'sugar': 9.85, '..."
11,Fig,68,Moraceae,Rosales,Ficus,"{'calories': 74, 'fat': 0.3, 'sugar': 16.0, 'c..."
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,"{'calories': 44, 'fat': 0.6, 'sugar': 0.0, 'ca..."
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,"{'calories': 97, 'fat': 0.7, 'sugar': 11.2, 'c..."
14,Plum,71,Rosaceae,Rosales,Prunus,"{'calories': 46, 'fat': 0.28, 'sugar': 9.92, '..."
15,Orange,2,Rutaceae,Sapindales,Citrus,"{'calories': 43, 'fat': 0.2, 'sugar': 8.2, 'ca..."
16,GreenApple,72,Rosaceae,Rosales,Malus,"{'calories': 21, 'fat': 0.1, 'sugar': 6.4, 'ca..."
17,Raspberry,23,Rosaceae,Rosales,Rubus,"{'calories': 53, 'fat': 0.7, 'sugar': 4.4, 'ca..."
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,"{'calories': 30, 'fat': 0.2, 'sugar': 6.0, 'ca..."
19,Lemon,26,Rutaceae,Sapindales,Citrus,"{'calories': 29, 'fat': 0.3, 'sugar': 2.5, 'ca..."
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,"{'calories': 60, 'fat': 0.38, 'sugar': 13.7, '..."
21,Blueberry,33,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
22,Apple,6,Rosaceae,Rosales,Malus,"{'calories': 52, 'fat': 0.4, 'sugar': 10.3, 'c..."
23,Guava,37,Myrtaceae,Myrtales,Psidium,"{'calories': 68, 'fat': 1.0, 'sugar': 9.0, 'ca..."
24,Apricot,35,Rosaceae,Rosales,Prunus,"{'calories': 15, 'fat': 0.1, 'sugar': 3.2, 'ca..."
25,Papaya,42,Caricaceae,Caricacea,Carica,"{'calories': 43, 'fat': 0.4, 'sugar': 1.0, 'ca..."
26,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,"{'calories': 34, 'fat': 0.0, 'sugar': 8.0, 'ca..."
27,Tangerine,77,Rutaceae,Sapindales,Citrus,"{'calories': 45, 'fat': 0.4, 'sugar': 9.1, 'ca..."
28,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,"{'calories': 36, 'fat': 0.4, 'sugar': 3.0, 'ca..."
29,Lime,44,Rutaceae,Sapindales,Citrus,"{'calories': 25, 'fat': 0.1, 'sugar': 1.7, 'ca..."
30,Pomegranate,79,Lythraceae,Myrtales,Punica,"{'calories': 83, 'fat': 1.2, 'sugar': 13.7, 'c..."
31,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,"{'calories': 60, 'fat': 1.5, 'sugar': 8.0, 'ca..."
32,Grape,81,Vitaceae,Vitales,Vitis,"{'calories': 69, 'fat': 0.16, 'sugar': 16.0, '..."
33,Morus,82,Moraceae,Rosales,Morus,"{'calories': 43, 'fat': 0.39, 'sugar': 8.1, 'c..."
34,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,"{'calories': 44, 'fat': 0.4, 'sugar': 3.0, 'ca..."
35,Avocado,84,Lauraceae,Laurales,Persea,"{'calories': 160, 'fat': 14.66, 'sugar': 0.66,..."
36,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,"{'calories': 61, 'fat': 0.5, 'sugar': 8.9, 'ca..."
37,Cranberry,87,Ericaceae,Ericales,Vaccinium,"{'calories': 46, 'fat': 0.1, 'sugar': 4.0, 'ca..."
38,Cherry,9,Rosaceae,Rosales,Prunus,"{'calories': 50, 'fat': 0.3, 'sugar': 8.0, 'ca..."
39,Peach,86,Rosaceae,Rosales,Prunus,"{'calories': 39, 'fat': 0.25, 'sugar': 8.4, 'c..."
40,Jackfruit,94,Moraceae,Rosales,Artocarpus,"{'calories': 95, 'fat': 0.0, 'sugar': 19.1, 'c..."
41,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,"{'calories': 44, 'fat': 1.26, 'sugar': 0.5, 'c..."
42,Hazelnut,96,Betulaceae,Fagales,Corylus,"{'calories': 628, 'fat': 61.0, 'sugar': 4.3, '..."
43,Pomelo,98,Rutaceae,Sapindales,Citrus,"{'calories': 37, 'fat': 0.0, 'sugar': 8.5, 'ca..."
44,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,"{'calories': 73, 'fat': 0.58, 'sugar': 16.11, ..."

In [48]:
df1 = pd.json_normalize(results)
df1.head()

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.0,18.0,18.0,0.0
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.4,5.4,5.5,0.8
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.2,17.2,22.0,1.0
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.2,2.6,3.9,0.9
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.1,10.0,15.0,0.4

In [52]:
#Get te family and genus of a cherry
cherry = df1.loc[df1['name']=='Cherry']
cherry

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
38,Cherry,9,Rosaceae,Rosales,Prunus,50,0.3,8.0,12.0,1.0

In [53]:
(cherry.iloc[0]['family']) , (cherry.iloc[0]['genus'])

('Rosaceae', 'Prunus')

In [56]:
# FINDING OUT HOW MANY CALORIES CONTAINED IN A BANANA
banana = df1.loc[df1['name'] == 'Banana']
banana

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.2,17.2,22.0,1.0

In [57]:
(banana.iloc[0]['nutritions.calories'])

96

### THE OFFICIAL JOKE API  
This API returns random jokes from the database

In [58]:
# Loading the data from URL
jokes = requests.get('https://official-joke-api.appspot.com/jokes/ten')
jokes

In [60]:
# getting the results
results = json.loads(jokes.text)
results

[{'type': 'general',
  'setup': 'Why did the Clydesdale give the pony a glass of water?',
  'punchline': 'Because he was a little horse!',
  'id': 324},
 {'type': 'general',
  'setup': 'Why did the scarecrow win an award?',
  'punchline': 'Because he was outstanding in his field.',
  'id': 339},
 {'type': 'general',
  'setup': "What's orange and sounds like a parrot?",
  'punchline': 'A Carrot.',
  'id': 272},
 {'type': 'general',
  'setup': 'Why did the belt go to prison?',
  'punchline': 'He held up a pair of pants!',
  'id': 321},
 {'type': 'general',
  'setup': 'What biscuit does a short person like?',
  'punchline': 'Shortbread. ',
  'id': 157},
 {'type': 'general',
  'setup': 'What did the digital clock say to the grandfather clock?',
  'punchline': 'Look, no hands!',
  'id': 171},
 {'type': 'general',
  'setup': 'Did you hear about the guy who invented Lifesavers?',
  'punchline': 'They say he made a mint.',
  'id': 89},
 {'type': 'general',
  'setup': 'Did you hear about the submarine industry?',
  'punchline': 'It really took a dive...',
  'id': 96},
 {'type': 'general',
  'setup': 'Why do bananas have to put on sunscreen before they go to the beach?',
  'punchline': 'Because they might peel!',
  'id': 346},
 {'type': 'general',
  'setup': 'Why did the cowboy have a weiner dog?',
  'punchline': 'Somebody told him to get a long little doggy.',
  'id': 328}]

In [62]:
# Converting into pandas dataframe
df = pd.DataFrame(results)
df.head()

,type,setup,punchline,id
0,general,Why did the Clydesdale give the pony a glass o...,Because he was a little horse!,324
1,general,Why did the scarecrow win an award?,Because he was outstanding in his field.,339
2,general,What's orange and sounds like a parrot?,A Carrot.,272
3,general,Why did the belt go to prison?,He held up a pair of pants!,321
4,general,What biscuit does a short person like?,Shortbread.,157

In [68]:
df.drop(columns = ['type','id'], inplace = True)
df.head()

,setup,punchline
0,Why did the Clydesdale give the pony a glass o...,Because he was a little horse!
1,Why did the scarecrow win an award?,Because he was outstanding in his field.
2,What's orange and sounds like a parrot?,A Carrot.
3,Why did the belt go to prison?,He held up a pair of pants!
4,What biscuit does a short person like?,Shortbread.